name: ChestShop
main: ChestShop\ChestShop
version: 1.5.1
api: [3.0.0-ALPHA11]
load: POSTWORLD
author: Skyladd
description: Open your ChestShop
permissions:
 chestshop:
  default: true
  description: "Allows using all the ChestShop things"
 chestshop.creative:
  default: op
  description: "Allows filling shops in creative mode"
 chestshop.manager:
  default: op
  description: "Allows breaking and opening others shops"
